general:
  kafka-topic: "test-topic"
  kafka-group-id: "test-group"

spring:
  kafka:
    consumer:
      group-id: "test-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

